### ISSUE TITLE
Field object has no attribute subfields

### ISSUE THREAD

**Issue by azaroth42** [edsu/pymarc#59]
For a 001 field, which doesn't have any subfields, trying to fetch them generates an exception rather than returning empty list.

>>> f.get_subfields()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pymarc-3.0.1-py2.6.egg/pymarc/field.py", line 155, in get_subfields
    for subfield in self:
  File "/usr/lib/python2.6/site-packages/six-1.7.3-py2.6.egg/six.py", line 518, in next
    return type(self).__next__(self)
  File "/usr/lib/python2.6/site-packages/pymarc-3.0.1-py2.6.egg/pymarc/field.py", line 126, in __next__
    while self.__pos < len(self.subfields):
AttributeError: 'Field' object has no attribute 'subfields'

**Comment by edsu** [comment]
I think this got fixed when #32 was merged. Please reopen if that's not the case.
