### ISSUE TITLE
Exception at the end of iterating through a marc file.

### ISSUE THREAD

**Issue by cshintov** [edsu/pymarc#97]
When I am Iterating through a marc file containing multiple MARC records, After the last record the following exception is raised. 
Traceback (most recent call last):
  File "compare_marcs.py", line 320, in <module>
    pprint(compare_marc_files(exp, obs))
  File "compare_marcs.py", line 299, in compare_marc_files
    for exp_marc, obs_marc in izip(expected, observed):
  File "/home/shinto/shinto/virtualenvs/marc/local/lib/python2.7/site-packages/six.py", line 558, in next
    return type(self).__next__(self)
  File "/home/shinto/shinto/virtualenvs/marc/local/lib/python2.7/site-packages/pymarc/reader.py", line 97, in __next__
    utf8_handling=self.utf8_handling)
  File "/home/shinto/shinto/virtualenvs/marc/local/lib/python2.7/site-packages/pymarc/record.py", line 74, in __init__
    utf8_handling=utf8_handling)
  File "/home/shinto/shinto/virtualenvs/marc/local/lib/python2.7/site-packages/pymarc/record.py", line 245, in decode_marc
    raise BaseAddressInvalid
pymarc.exceptions.BaseAddressInvalid: Base address exceeds size of record

**Comment by Wooble** [comment]
It sounds like your file might be cut off before the end of the last record, or at least pymarc thinks so. How are you opening the file and creating the reader?

**Comment by cshintov** [comment]
Hi I am opening the files using 'with' .
exp and obs are the two marc files.

with open(exp) as exp_marcs, open(obs) as obs_marcs:
        for exp_marc, obs_marc in izip(expected, observed):
                   do stuff

Thanks,
Shinto.

**Comment by edsu** [comment]
That's an interesting way to do it. And by interesting I mean I have no idea what it does :-) Can you explain what's going on there?
